[workspace]
resolver = "2"
members = [
    "configuration-nix",
    "bootstrap-config-builder",
    "flake-template-generator",
    "prelude-generator",
    "rust-decl-splitter",
    "rust-system-composer",
    "vendor/rarrow",
]
