[workspace]
resolver = "3"
members = [
    "standalonex/src/bootstrap/src/core/config_utils",
    "standalonex/src/bootstrap/src/core/config_processor",
    "standalonex/src/stage0_parser_crate",
    "configuration-nix",
    "bootstrap-config-builder",
    "standalonex/src/bootstrap/src/core/config_crates/config_tests", "flake-template-generator",
]
