# Topological Order of Tasks
tasks = [
    "13_01_vendorize_all_rust_dependencies.toml",
    "03_08_generate_per_file_projects.toml",
    "04_04_develop_integration_tests.toml",
    "01_09_rebuild_lattice_with_split_dependencies.toml",
    "03_05_determine_project_root.toml",
    "03_17_process_raw_dumps_and_traces.toml",
    "01_03_define_api_for_flake_generation.toml",
    "01_02_create_new_module_crate_for_flake_generation.toml",
    "01_05_generate_initial_flakes_for_each_crate.toml",
    "06_10_generate_unique_module_paths_for_declaration_groups.toml",
    "03_15_execute_instrumented_builds_for_all_projects.toml",
    "03_14_integrate_instrumentation_with_cargo_build.toml",
    "03_02_build_hf_dataset_validator.toml",
    "03_21_group_declarations_into_client_crates.toml",
    "11_08_integrate_bootstrap_config_builder_core.toml",
    "06_18_implement_preprocessfunctor_for_refining_use_statement_classification.toml",
    "03_13_develop_compiler_instrumentation_tool.toml",
    "06_11_generate_canonical_prelude_rs_with_pub_use_statements.toml",
    "01_11_define_layered_dependency_structure.toml",
    "01_08_differentiate_module_and_declaration_dependencies.toml",
    "06_16_implement_extractusesfunctor_for_parsed_file_to_use_statements_extraction.toml",
    "02_07_refine_classify_uses_functor.toml",
    "04_05_enhance_end_to_end_scripts.toml",
    "01_01_identify_existing_flake_generation_logic.toml",
    "02_05_generate_toml_report_for_bag_of_words.toml",
    "03_03_define_output_directory_for_raw_data.toml",
    "02_02_refactor_prelude_generator_main_rs.toml",
    "06_09_implement_coordinate_grouping_logic_for_declarations.toml",
    "03_12_generate_projects_with_monadic_io_integration.toml",
    "06_12_integrate_symbol_table_for_primitives_and_modules.toml",
    "03_10_define_monadic_io_traits_and_arrow_composition.toml",
    "evaluate_plantuml_crates.toml",
    "06_06_apply_introspective_rollup_workflow_for_ai_analysis.toml",
    "03_11_refactor_rust_system_composer_to_use_monadic_io.toml",
    "03_18_extract_constants_names_and_ids.toml",
    "03_19_build_level_0_knowledgebase_index.toml",
    "03_23_format_knowledgebase_for_minizinc.toml",
    "03_04_create_output_directory_for_raw_data.toml",
    "crash_report_20251104_120000.toml",
    "03_09_verify_compilation_of_generated_projects.toml",
    "05_07_assign_dependency_levels_to_extracted_functions.toml",
    "03_06_execute_hf_dataset_validator_for_metadata_and_dependencies.toml",
    "01_06_analyze_crate_dependencies.toml",
    "06_17_implement_classifyusesfunctor_for_use_statement_classification.toml",
    "06_08_implement_structured_declaration_representation.toml",
    "06_14_implement_stage_2_preprocess_synerror_use_statements.toml",
    "06_07_enhance_declsvisitor_to_collect_bag_of_words_for_declarations.toml",
    "04_01_review_existing_tests.toml",
    "01_12_controlled_external_library_introduction.toml",
    "02_03_refine_hierarchical_directory_structure_for_constants.toml",
    "00_00_recreate_rust_compiler_with_lattice.toml",
    "12_01_metrics_reporter_rollup_report.toml",
    "12_03_implement_optimization_refactoring_analysis.toml",
    "09_01_maintain_core_vision_docs.toml",
    "09_04_maintain_binary_documentation.toml",
    "09_03_enforce_shellcheck_in_ci.toml",
    "09_05_refine_gitignore_strategy.toml",
    "12_15_mandate_one_external_crate_per_module.toml",
    "12_08_enforce_functor_purity.toml",
    "02_01_implement_bag_of_words_and_coordinate_grouping_for_declarations.toml",
    "12_02_implement_lattice_placement_logic.toml",
    "02_10_implement_layered_usage_reporting.toml",
    "08_01_implement_structured_logging.toml",
    "05_08_extract_base_level_0_declarations.toml",
    "08_03_enhance_error_handling.toml",
    "fix_prelude_generator_invalid_code_gen.toml",
    "12_06_generate_flake_template_modifications.toml",
    "12_11_refactor_expand_macros_and_parse.toml",
    "06_01_decompose_codebase_into_granular_components_using_rust_decl_splitter.toml",
    "06_19_extract_syn_usage_into_syn_lattice.toml",
    "06_24_create_syn_usage_collector_crate.toml",
    "06_02_map_internal_and_external_dependencies_for_lattice_construction.toml",
    "06_03_apply_topological_sorting_to_codebase_components.toml",
    "06_04_canonicalize_and_refactor_components_one_external_crate_per_module.toml",
    "12_17_isolate_level0_declarations.toml",
    "12_12_ensure_full_trait_population_in_usestatement.toml",
    "00_01_architectural_principle_lattice_from_self_contained_entities.toml",
    "11_01_fix_prelude_generator_compilation_errors.toml",
    "10_01_best_practices_adherence.toml",
    "06_20_sub_lattice_of_large_types.toml",
    "06_21_analyze_enum_extension_lattice.toml",
    "06_22_analyze_struct_field_co_occurrence_lattice.toml",
    "02_04_implement_global_index_and_8d_embedding_for_all_constants.toml",
    "12_16_complete_librs_refactoring.toml",
    "05_04_generate_new_prelude_generator_version_from_hugging_face_dataset.toml",
    "01_10_define_canonical_lib_layer_0.toml",
    "12_14_decouple_api_types_using_traits.toml",
    "12_09_apply_shared_ownership_concurrency_rigor.toml",
    "12_18_resolve_rust_system_composer_main.toml",
    "07_05_evaluate_bootstrap_config_builder_decomposition.toml",
    "11_02_fix_generated_test_runner.toml",
    "12_10_decompose_huggingface_validator_functor.toml",
    "02_06_resolve_rust_system_composer_main_function_location.toml",
    "00_01_demonstrate_lattice_splitting.toml",
    "07_03_break_down_monolithic_functions.toml",
    "06_13_implement_stage_1_classify_use_statements.toml",
    "09_02_verify_onboarding_guide.toml",
    "12_13_utilize_ast_statistics_for_classification_heuristics.toml",
    "05_01_apply_prelude_generator_to_its_own_source_code.toml",
    "03_07_refactor_rust_system_composer_as_orchestrator.toml",
    "03_16_nixify_cargo_expand_output_capture.toml",
    "12_04_implement_formal_specification_generation.toml",
    "12_19_implement_reconstruct_ast_from_hf_dataset.toml",
    "01_04_discover_all_cargo_crates_in_current_repository.toml",
    "02_08_refine_preprocess_functor.toml",
    "03_20_extract_declaration_level_crate_usage.toml",
    "14_02_fix_workspace_build_failures.toml",
    "14_01_refine_rust_system_composer_output_and_reporting.toml",
    "07_02_refine_prelude_collector_for_deduplication.toml",
    "08_02_sanitize_sensitive_paths.toml",
    "06_05_re_compose_transformed_components_into_lattice_structured_codebase.toml",
    "06_05_01_run_regenerate_generated_projects_make_target.toml",
    "05_06_extract_functions_in_canonical_form.toml",
    "11_03_implement_reconstruct_ast_from_hf_dataset.toml",
    "02_09_utilize_generated_data_for_self_generation.toml",
    "05_02_generate_ast_from_prelude_generator_source_code.toml",
    "05_03_save_ast_and_use_statement_info_to_hugging_face_dataset.toml",
    "08_04_sanitize_error_collection.toml",
    "05_05_integrate_hugging_face_dataset_validator_into_source_scanning.toml",
    "07_01_generate_workspace.toml",
    "02_11_implement_leveled_report_type_t_usage.toml",
    "13_02_implement_layered_declaration_processing.toml",
    "04_02_prioritize_test_cases.toml",
    "03_01_identify_cargo_projects_in_nix.toml",
    "01_07_construct_flake_lattice.toml",
    "06_15_implement_parsefunctor_for_raw_file_to_parsed_file_transformation.toml",
    "04_03_expand_unit_test_coverage.toml",
    "06_23_generate_8d_sublattices_and_organize_libs.toml",
    "07_04_enforce_library_binary_separation.toml",
    "12_07_implement_compiler_heuristic_generation.toml",
    "03_24_execute_minizinc_solver.toml",
    "03_22_decouple_api_types_using_traits.toml",
    "12_05_generate_declaration_updates.toml",
]
