[package]
name = "test_generate_prelude_no_force_no_overwrite"
version = "0.1.0"
edition = "2021"

[dependencies]
prelude = { path = "../../prelude" }
serde = { version = "1.0", features = ["derive"] }
