[package]
name = "test_definitions_macro"
version = "0.1.0"


[lib]
proc-macro = true

[dependencies]
quote = "1.0.41"
syn = "2.0.108"
#syn = { version = "2.0", features = ["full"] }
#quote = "1.0"
#proc-macro2 = "1.0.103"
#proc_macro = "*"

