[package]
name = "metrics-reporter"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
tempfile = "3.10.1"
walkdir = "2.5.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
