[package]
name = "prelude-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
walkdir = "2"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
prettyplease = "0.2"
dunce = "1.0"
prelude-collector = { path = "../generated/crates/prelude-collector" }
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
