[package]
name = "flake-template-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
#serde = 
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8"
