[package]
name = "rust-decl-splitter"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.41"
syn = { version = "2.0.108", features = ["full", "visit"] }
walkdir = "2.5.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
