[package]
name = "generate_test_verification_script_and_report"
version = "0.1.0"
edition = "2021"

[dependencies]
prelude = { path = "../../prelude" }
serde = { version = "1.0", features = ["derive"] }
