[package]
name = "handle_collect_and_process_use_statements"
version = "0.1.0"
edition = "2021"

[dependencies]
prelude = { path = "../../prelude" }
serde = { version = "1.0", features = ["derive"] }
