[package]
name = "prelude-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.23.0"
sha2 = "0.10"
indoc = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
walkdir = "2"
toml = "0.8"